@startuml 传感器与主机交互
left to right direction
skinparam packageStyle rectangle
actor 传感器 as sensor
actor 控制器 as controller
actor 服务器 as server
rectangle 传感器、控制、服务器与主机交互{
    sensor - (设备连接)
    controller - (设备连接)
    sensor -down- (测量环境数据)
    controller -down- (执行控制命令)
    (设备连接) --> (主程序循环)
    (主程序循环) .up.> (测量环境数据):include
    (主程序循环) ..> (发送环境数据):include
    (主程序循环) ..> (接收控制命令):include
    (主程序循环) .up.> (执行控制命令):include
    (发送环境数据) -- server
    (接收控制命令) -- server
}

@enduml