@startuml 服务器与用户及设备交互
left to right direction
skinparam packageStyle rectangle
actor 用户 as user
rectangle 服务器与用户及设备交互{
    user -- (登录界面)
    user -- (查看数据)
    user -- (控制设备)
    (查看数据) --> (数据管理)
    (控制设备) --> (设备管理)
    (数据管理) ..> (数据接收)
    (数据管理) ..> (数据操作)
    (设备管理) ..> (设备信息操作)
    (设备管理) ..> (命令发送)
    (数据接收) --> (设备交互接口)
    (命令发送) --> (设备交互接口)
}
actor 设备 as device
(设备交互接口) -- device
@enduml