@startuml 传感器类图
class "Sensor" as sensor {
    DeviceID : long
    condition : string
    calculagraph() : void
}

class "Parameter" as parameter {
    +atmosphere_humidity : float
    +soil_humidity : float
    +atmosphere_temperature : float
    +illumination : uint16_t
    ' uinit16_t 即 unsigned short int
    +CO2_concentration : uint16_t
    ' PPM
    +soil_PH : float
    +time : time_t
    ' 唯一时间戳
    +measureParameter() : void
    ' 考虑使用 JSON 来传输数据
    +calibration() : void
}

interface "Request Parameter" as request {
    setDeviceID(long) : void
    getParameter() : void
    getDeviceID() : long
    restartDevice() : void
}

sensor ..> parameter
sensor .right.|> request

@enduml
