@startuml 主机设备与服务器交互活动图
|服务器|
start
while (系统连接正常)
    :处理收到的数据;
    while (判断决策) is (需要进行控制)
        :向主机设备发送\n控制命令;
        |主机设备|
        :接收命令;
        :返回接收确认;
        :向主机设备发送\n下一次数据请求;
    endwhile (不需要进行控制)
    |服务器|
    :返回初始状态;
endwhile
stop
@enduml