@startuml 主机设备与控制器交互活动图
|主机设备|
start
while (系统连接正常)
    :检测是否收到命令;
    while (条件判断) is (收到命令)
    :返回接收确认;
    :控制相应设备;
    |控制器|
    :执行动作;
    :返回执行确认;
    endwhile (没有收到命令)
    |主机设备|
endwhile
stop
@enduml