@startuml 主机状态图
[*] -right-> 等待状态
等待状态 : 循环计时
等待状态 : 监听端口
等待状态 -up-> 数据测量状态:计时器到时
state 数据测量状态 {
    [*] -down-> 请求环境数据
    请求环境数据 -down-> 准备接收数据:发送请求信息
    准备接收数据 -right-> 数据接收完成:发送确认信息
    数据接收完成 -up-> 数据测量完成:存储数据
    数据测量完成 -up-> [*]
} 
数据测量状态 -right-> 数据发送状态:测量后发送数据
state 数据发送状态 {
    [*] -down-> 准备发送数据
    准备发送数据 -down-> 连接就绪:建立连接
    连接就绪 -right-> 等待接收确认:发送数据
    等待接收确认 -up-> 发送完成:接收确认
    发送完成 -up-> [*]
}
数据发送状态 --> 等待状态

等待状态 -down-> 命令接收状态:收到服务器请求
state 命令接收状态 {
    [*] -down-> 准备接收命令:连接建立
    准备接收命令 -right-> 命令接收完成:接收命令信息
    命令接收完成 -up-> [*]:发送确认信息
}
命令接收状态 -right-> 命令执行状态
state 命令执行状态 {
    [*] -down-> 准备执行控制命令
    准备执行控制命令 -right-> 执行状态:控制相应器件
    执行状态 : 计时器
    执行状态 : 条件检查器
    执行状态 -right-> 执行完成状态:达到相应条件
    执行完成状态 -up-> [*]
}
命令执行状态 -->等待状态
等待状态 -right-> [*]
@enduml