@startuml 内部环境状态图
[*] -right-> 环境稳定状态
环境稳定状态 --> 环境稳定状态:保持稳定
环境稳定状态 -down-> 参数超出阈值:环境出现变动
参数超出阈值 -right-> 调整状态
参数超出阈值 : 环境温度
参数超出阈值 : 土壤湿度
参数超出阈值 : 光照强度
参数超出阈值 : (可选其他环境参数)
state 调整状态(可并发) {
    [*] -right-> 环境温度异常
    环境温度异常 -right-> 环境温度正常:温度调节(冷热)
    环境温度正常 -right-> [*]
    --
    [*] -up-> 湿度过高
    湿度过高 -right-> 湿度下降:通风排湿
    [*] -down-> 湿度过低
    湿度过低 -right-> 湿度回升:喷淋灌溉
    湿度下降 -down-> [*]
    湿度回升 -up-> [*]
    --
    [*] -up-> 太阳光照过强
    太阳光照过强 -right-> 光照降低:打开遮阳网
    [*] -down-> 阴天光照不足
    阴天光照不足 -right-> 照明充足:开启补光灯
    光照降低 -down-> [*]
    照明充足 -up-> [*]
    --
    [*] -right-> 其他环境参数异常
    其他环境参数异常 -right-> 环境参数正常:执行相应操作
    环境参数正常 -right-> [*]
}
调整状态 -left-> 环境稳定状态
@enduml